stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build-job:
  image: docker:latest
  stage: build

  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD --password-stdin
    - docker build -t $CI_REGISTRY_USER/grupo-tdd1/backend-tdd .
    - docker push $CI_REGISTRY_USER/grupo-tdd1/backend-tdd


deploy-job:      
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
