stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build-job:
  image: docker:latest
  stage: build

  script:
    - echo $CI_REGISTRY_PASSWORD $CI_REGISTRY_USER

deploy-job:      
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
