stages: 
  - build
  - deploy

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest

build-job:
  stage: build
  script:
    - docker build -t $TAG_LATEST .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $TAG_LATEST
  only:
    - main


deploy-job:      
  stage: deploy
  environment: production
  script:
    - docker-compose down
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $TAG_LATEST
    - docker-compose up -d
  only:
    - main
