stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build-job:
  image: docker:latest
  stage: build

  script:
    - docker build -t registry.gitlab.com/grupo-tdd1/backend-tdd .
    - docker push registry.gitlab.com/grupo-tdd1/backend-tdd

deploy-job:      
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."