services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "34001:8080"

  db:
    image: postgres:12.16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "34003:5432"
