services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "34001:8080"
  postgres:
    image: postgres:12.16
    container_name: tdd_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "34003:5432"
    volumes:
      - ../backend-data/data/postgres:/var/lib/postgresql/data
