services:
  web:
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - JWT_KEY=$JWT_KEY
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "$PORTS_API"
  postgres:
    image: postgres:12.16
    container_name: tdd_db      
    ports:
      - "$PORTS_DB"
    volumes:
      - $HOME/tdd-backend-data/data/postgres:/var/lib/postgresql/data
